version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: ./TBC/clientapp
      dockerfile: Dockerfile
    container_name: TBC_Frontend
    expose:
      - "80"

  api:
    build:
      context: .
      dockerfile: ./TBC/Dockerfile
    container_name: TBC_Api
    expose:
      - "80"
    depends_on:
      - db

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - ConnectionStrings__Default=Host=db;Port=5432;Database=TBCdb;Username=postgres;Password=secret

  db:
    image: postgres:17
    container_name: TBC_Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: TBCdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
