services:
  api:
    build:
      context: ./TBC            # <-- здесь ваш ASP.NET-проект
      dockerfile: Dockerfile
    container_name: TBC_Api
    expose:
      - "80"
    depends_on:
      - db
