version: '3.8'

services:
  tbc:
    build:
      context: ./TBC
      dockerfile: Dockerfile
    container_name: TBC
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./tbc/clientapp
      dockerfile: Dockerfile
    container_name: TBC_Frontend
    ports:
      - "3000:80"
    depends_on:
      - tbc
