services:
  tbc:
    container_name: TBC
    build:
      context: ./TBC
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_URLS: "http://+:8080;https://+:8081"