name: CI – build & push (master)

on:
  push:
    branches: [ master ]      # ← только master
    tags:     [ 'v*' ]        # ← и все версии вида v1.2.3
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write         # даёт GITHUB_TOKEN право push-ить в ghcr

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # buildx + (опц.) QEMU, если нужны arm64
    - uses: docker/setup-buildx-action@v3
    - uses: docker/setup-qemu-action@v3    # можно убрать, если только amd64

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta (теги/лейблы)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/api
        tags: |
          type=ref,event=branch             # latest для master
          type=sha,format=short             # sha-abcdef
          type=semver,pattern={{version}}   # v1.2.3, если есть тег
        labels: |
          org.opencontainers.image.source=${{ github.repositoryUrl }}

    - name: Build & push API image
      uses: docker/build-push-action@v5
      with:
        context: ./TBC           # путь к исходникам
        file: ./TBC/Dockerfile   # мульти-стейдж Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha     # кэш слоёв в GitHub
        cache-to:   type=gha,mode=max
